### ISSUE TITLE
Unable to pause recording correctly on iOS

### ISSUE THREAD

**Issue by Linspirit98** [natmlx/NatCorder-Performance-Extensions#1]
I am trying to pause recording and my code is given below. However, the realTimeClock is not pausing when I try after building my app on iOS. However, it works in unity. This results in my video keeps on recording but the frame is stuck at the last frame before pausing. I can't find out the reason why this happened. Can you offer any suggestions? Thank you.

```
Debug.Log("Pausing Recording...");
// Stop the realtime clock
clock.paused = true;
// This will effectively pause recording
cameraInput.Dispose();
audioInput.Dispose();
```

**Comment by olokobayusuf** [comment]
Can you share your code when you un-pause?

**Comment by Linspirit98** [comment]
> Can you share your code when you un-pause? And can you share the code for creating a recorder?


This is for creating recorder: 
```
recorder = new MP4Recorder(videoWidth, videoHeight, frameRate, AudioSettings.outputSampleRate,(int)AudioSettings.speakerMode);
cameraInput = new CameraInput(recorder, clock, recordCamera);
audioListener = recordCamera.GetComponent<AudioListener>();
if (audioListener != null) audioInput = new AudioInput(recorder, clock, audioListener);
```

And this for resuming:
```
clock.paused = false;
cameraInput = new CameraInput(recorder, clock, recordCamera);
audioListener = recordCamera.GetComponent<AudioListener>();
if (audioListener != null) audioInput = new AudioInput(recorder, clock, audioListener);
```

**Comment by olokobayusuf** [comment]
I'll try to reproduce this and get back to you. Thanks for bringing it up.

**Comment by Linspirit98** [comment]
> I'll try to reproduce this and get back to you. Thanks for bringing it up.

I also found that the number of frames in the video is different from the number of frames in the file attributes. This happens not only on iOS but also android. Maybe you can check this? Thank you.

**Comment by olokobayusuf** [comment]
We've fixed an issue where the `RealtimeClock` was not pausing properly. I'm closing this issue. If you face any similar issue with the latest version of NatCorder, feel free to open another issue.
